#!/bin/bash -e

. ./hooks/env

#HOSTED_ZONE_ID=
DNS_NAME=dockertest
AWS_REGION=us-east-1
AWS_PROFILE=admin

docker run -it --rm \
    -e AWS_REGION=${AWS_REGION} \
    -e HOSTED_ZONE_ID=${HOSTED_ZONE_ID} \
    -e DNS_NAME=${DNS_NAME} \
    -e AWS_PROFILE=${AWS_PROFILE} \
    -v ~/.aws:/root/.aws \
    ${IMAGE_NAME}
