#!/bin/bash -e

. ./hooks/env

docker run --rm --entrypoint /usr/bin/aws ${IMAGE_NAME} --version
docker run --rm --entrypoint /usr/bin/grepcidr ${IMAGE_NAME} -V | grep -F 'grepcidr 2.0'
docker run --rm --entrypoint /usr/bin/curl ${IMAGE_NAME} --version
